version: '3'
services:
  coti-exchange-app:
    image: exchangeapp/exchangeapp:latest
    ports:
      - "1337:1337"
    restart: on-failure
    command: ["sails","lift"]
    volumes:
      - ./db/:/app/db
      - .env.json:/app/.env.json
      - ./log:/app/log
